export const algorithmPseudocode: Record<string, string[]> = {
  bubble: [
    '// Bubble Sort',
    'n = array.length',
    'for i = 0 to n - 1',
    '  swapped = false',
    '  for j = 0 to n - i - 1',
    '    if array[j] > array[j+1]',
    '      swap(array[j], array[j+1])',
    '      swapped = true',
    '  if not swapped break',
    'return array'
  ],
  selection: [
    '// Selection Sort',
    'n = array.length',
    'for i = 0 to n - 1',
    '  min_idx = i',
    '  for j = i + 1 to n',
    '    if array[j] < array[min_idx]',
    '      min_idx = j',
    '  if min_idx != i',
    '    swap(array[i], array[min_idx])',
    'return array'
  ],
  insertion: [
    '// Insertion Sort',
    'n = array.length',
    'for i = 1 to n',
    '  key = array[i]',
    '  j = i - 1',
    '  while j >= 0 and array[j] > key',
    '    swap(array[j], array[j+1])',
    '    j = j - 1',
    '  array[j+1] = key',
    'return array'
  ],
  merge: [
    '// Merge Sort',
    'function mergeSort(arr, l, r)',
    '  if l >= r return',
    '  mid = l + (r - l) / 2',
    '  mergeSort(arr, l, mid)',
    '  mergeSort(arr, mid + 1, r)',
    '  merge(arr, l, mid, r)',
    '// Merge arrays conceptually...'
  ],
  quick: [
    '// Quick Sort',
    'function partition(arr, low, high)',
    '  pivot = array[high]',
    '  i = low - 1',
    '  for j = low to high',
    '    if array[j] < pivot',
    '       i++',
    '       swap(array[i], array[j])',
    '  swap(array[i+1], array[high])'
  ],
  dijkstra: [
    '// Dijkstra\'s Algorithm',
    'distances[start] = 0',
    'while unvisited is not empty',
    '  node = unvisited with min distance',
    '  if distance == Infinity break',
    '  if node == target reconstruct_path(); return;',
    '  for neighbor in getNeighbors(node)',
    '    alt = distances[node] + 1',
    '    if alt < distances[neighbor]',
    '      distances[neighbor] = alt',
    '      parent[neighbor] = node'
  ],
  astar: [
    '// A* Search',
    'gScore[start] = 0',
    'fScore[start] = heuristic(start, target)',
    'while openSet is not empty',
    '  curr = openSet node with min fScore',
    '  if curr == target reconstruct_path(); return;',
    '  for neighbor in getNeighbors(curr)',
    '    tentative_gScore = gScore[curr] + 1',
    '    if tentative_gScore < gScore[neighbor]',
    '      parent[neighbor] = curr',
    '      gScore[neighbor] = tentative_gScore',
    '      fScore[neighbor] = tentative_gScore + heuristic(n, target)'
  ],
  avl: [
    '// AVL Tree Insertion',
    'function insert(node, key)',
    '  if node == null return new Node(key)',
    '  if key < node.key node.left = insert(node.left, key)',
    '  else node.right = insert(node.right, key)',
    '  ',
    '  node.height = 1 + max(height(node.left), height(node.right))',
    '  balance = getBalance(node)',
    '  ',
    '  // Left Left Case',
    '  if balance > 1 and key < node.left.key return rightRotate(node)',
    '  // Right Right Case',
    '  if balance < -1 and key > node.right.key return leftRotate(node)',
    '  // Left Right Case',
    '  if balance > 1 and key > node.left.key',
    '      node.left = leftRotate(node.left)',
    '      return rightRotate(node)',
    '  // Right Left Case',
    '  if balance < -1 and key < node.right.key',
    '      node.right = rightRotate(node.right)',
    '      return leftRotate(node)',
    '  return node'
  ],
  bst: [
    '// Binary Search Tree Insertion',
    'function bstInsert(node, key)',
    '  if node == null return new Node(key)',
    '  if key < node.key',
    '      node.left = bstInsert(node.left, key)',
    '  else',
    '      node.right = bstInsert(node.right, key)',
    '  return node'
  ],
  greedy: [
    '// Greedy Best-First Search',
    'openSet.push(start)',
    'while openSet is not empty',
    '  openSet.sortByHeuristic()',
    '  curr = openSet.pop()',
    '  if curr == target reconstruct_path(); return',
    '  for neighbor in getNeighbors(curr)',
    '    if neighbor not in visited',
    '      visited.add(neighbor)',
    '      parent[neighbor] = curr',
    '      openSet.push(neighbor)'
  ],
  bidir: [
    '// Bidirectional Search',
    'queueA.push(start); queueB.push(target)',
    'while queues are not empty',
    '  // Expanding from Start Front',
    '  currA = queueA.pop()',
    '  for neighbor in getNeighbors(currA)',
    '    if neighbor visited by B return intersect',
    '    if neighbor unvisited queueA.push(neighbor)',
    '  // Expanding from Target Front',
    '  currB = queueB.pop()',
    '  for neighbor in getNeighbors(currB)',
    '    if neighbor visited by A return intersect',
    '    if neighbor unvisited queueB.push(neighbor)'
  ],
  bfs: [
    '// Breadth-First Search',
    'queue.push(start)',
    'while queue is not empty',
    '  curr = queue.pop()',
    '  if curr == target reconstruct_path(); return;',
    '  for neighbor in getNeighbors(curr)',
    '    if neighbor not visited',
    '      mark_visited(neighbor)',
    '      parent[neighbor] = curr',
    '      queue.push(neighbor)'
  ],
  dfs: [
    '// Depth-First Search',
    'stack.push(start)',
    'while stack is not empty',
    '  curr = stack.pop()',
    '  if curr == target reconstruct_path(); return;',
    '  for neighbor in getNeighbors(curr)',
    '    if neighbor not visited',
    '      mark_visited(neighbor)',
    '      parent[neighbor] = curr',
    '      stack.push(neighbor)'
  ]
};
